name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'pages/**'
      - 'public/**'
      - '.vitepress/**'
  schedule:
    - cron: '0 8-23 * * *'  
  workflow_dispatch:
