name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_URL: "Gaozx1/Gaozx1.github.io"
      BUILD_PATH: ".vitepress/dist"
      CUSTOM_DOMAIN: "mcapple.top"

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm build

      - name: Deploy to GitHub Pages
        run: |
          cd $BUILD_PATH       
          echo "$CUSTOM_DOMAIN" > CNAME
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git checkout -B pages
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.REPO_URL }}.git
          git push --force origin pages
        env:
          CI: true